os: osx
language: objective-c
matrix:
  include:
    - {osx_image: xcode8.3, env: 'SWFT=3.1 PLAT=macOS DST="arch=x86_64"'}
    - {osx_image: xcode8.3, env: 'SWFT=3.1 PLAT=iOS   DST="OS=10.3.1,name=iPhone SE"'}

    - {osx_image: xcode9.2, env: 'SWFT=3.2 PLAT=macOS DST="arch=x86_64"'}
    - {osx_image: xcode9.2, env: 'SWFT=3.2 PLAT=iOS   DST="OS=11.2,name=iPhone SE"'}

    - {osx_image: xcode9.4, env: 'SWFT=3.3 PLAT=macOS DST="arch=x86_64"'}
    - {osx_image: xcode9.4, env: 'SWFT=3.3 PLAT=iOS   DST="OS=11.4,name=iPhone 5s"'}

    - {osx_image: xcode9.2, env: 'SWFT=4.0 PLAT=macOS DST="arch=x86_64"'}
    - {osx_image: xcode9.2, env: 'SWFT=4.0 PLAT=iOS   DST="OS=11.2,name=iPhone SE"'}
    
    - {osx_image: xcode9.4, env: 'SWFT=4.1 PLAT=macOS DST="arch=x86_64" TEST=1'}
    - {osx_image: xcode9.4, env: 'SWFT=4.1 PLAT=iOS   DST="OS=11.4,name=iPhone 5s" TEST=1'}
cache:
  directories:
  - Carthage
before_install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLAT --verbose
install:
  - xcodebuild -scheme PMKEventKit -target PMKEventKit -quiet -destination "$DST" SWIFT_VERSION=$SWFT SWIFT_TREAT_WARNINGS_AS_ERRORS=YES build
  - if [[ $TEST == 1 ]]; then
      xcodebuild -scheme PMKEventKit -target PMKEKTests -quiet -destination "$DST" build;
    fi
script:
  - if [[ $TEST == 1 ]]; then
      xcodebuild -scheme PMKEventKit -quiet -destination "$DST" test;
    fi
