git:
  depth: 1
  submodules: false
jobs:
  include:
    - stage: test
      language: swift
      os: osx
      osx_image: xcode9.4
      before_install:
      - brew update
      install:
      - Utils/ci-install-macos.sh
      before_script:
      - Utils/prepare-workspace-macos.sh
      script:
      - Utils/ci-script-macos.sh
    - language: generic
      os: linux
      dist: trusty
      install:
      - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
      - Utils/ci-script-linux.sh
    - stage: deploy
      if: tag IS present
      language: generic
      os: osx
      osx_image: xcode9.4
      env:
        secure: iavIkrus2Xd3b086nz2srMGl52yqzLuCdhyEAhMODVqkzqMQ17s10y1TNb+vkepd0HgxI9j57d5X7tfChjWuWDwE2hZKjr/Kx2DfiUr1AKQD6ymuGrq/0Vv6yL9dfPU8goFArcrsBcyVKczLtTuLCKL498ZqokkQc/3kGvzW74lv+z410MfHS9/tvToO/yXJckL6qJ2XBAiElfOO0rEkllTeCo6N3bjcHZ2o7PE0K+CHYxwNKj0TmPmuNWZ3U4fzoWzkk01re1C1l5cpSb20g+2aGyi0yYX+PomX7fIIqNq9vmmyoeNdr35yqoQv/0zFeFnps83NKmZLAjSUhiUdhlbuBLBE+w8544LOaZnMDlFmpDjgyaVnRrOh0NrBB1FwU48aGfX5ljRQmk/07FTEUjvwvGGoOpz8lrLZi148FMHEospL3Sf7d8K+Q9WdtLTGk7HCnbOVcxS6oB/SWF/Cj6n5wu+EI1floBaZEsNPR40Gd4eM/Ik/E3lDrZThGDCWQsao981wm7IfEDBR1nuMME8gpZINFANNS1+5miFaGdTnDTp4Yd5MGEFZm+K8x+TG1891NwNH1ZmKXlypJXiUzvSjbh2ViNJGekdQj9q2gj2ZFlCfHJ05adwJ4w9qRuF00HpAOD6At6EnsjDXFJeTZS5dj8fi2YsU9or8KfTFoNY=
      before_install:
      - brew update
      install:
      - Utils/ci-install-deploy.sh
      before_deploy:
      - >
        if ! [ "$BEFORE_DEPLOY_RUN" ]; then
          export BEFORE_DEPLOY_RUN=1;
          Utils/prepare-workspace-macos.sh -T;
          Utils/ci-before-deploy.sh;
        fi
      deploy:
      - provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file: "SWCompression.framework.zip"
        on:
          tags: true
      - provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs
        on:
          tags: true
          # Don't upload documentation if it is a test release.
          condition: $(git describe) != *"test"*
