version: git-{branch}-{build}
os: Visual Studio 2015

environment:
  matrix:
  - Toolset: v140

platform:
  - x86
  - x64

configuration:
# - Release-140
  - Debug-140
  
build:
  project: shell/reicast.sln
  parallel: true
  verbosity: minimal

after_build:
  - cmd: mkdir artifacts
  - cmd: set PLATFORM2=%PLATFORM:x86=Win32%
  - cmd: move WorkDir\reicast_%PLATFORM2%_%CONFIGURATION%.exe artifacts/reicast-win_%PLATFORM%-slow-%APPVEYOR_REPO_COMMIT%.exe

artifacts:
  - path: artifacts
    name: reicast-win_$(platform)-slow-$(APPVEYOR_REPO_COMMIT)

deploy:
- provider: S3
  access_key_id: AKIAJETEBUZSLZF3YNKA
  secret_access_key:
    secure: ZxrysCeqMK99dOOzKyoeN4R5aO8JjA4RTrwVAQPQHz8sjyyKuVDZT2fC+9m6lUIi
  region: eu-west-1
  bucket: reicast-builds-windows
  folder: 'builds/heads/$(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_REPO_COMMIT)'
  artifact: reicast-win_$(platform)-slow-$(APPVEYOR_REPO_COMMIT)
  set_public: true
