image: Visual Studio 2022

shallow_clone: true


environment:
  matrix:
    - Platform: x64
    - Platform: Win32

  Configuration: Release

  SDL2_version: 2.0.22


install:
  - cmd: |
      curl -o "C:\SDL2-devel.zip" "https://www.libsdl.org/release/SDL2-devel-%SDL2_version%-VC.zip"
      7z x "C:\SDL2-devel.zip" -o"C:\"
      xcopy /S "C:\SDL2-%SDL2_version%\include" src\common

      if %Platform%==x64 xcopy /S "C:\SDL2-%SDL2_version%\lib\x64" src\windows
      if %Platform%==Win32 xcopy /S "C:\SDL2-%SDL2_version%\lib\x86" src\windows


build_script:
  - cmd: |
      msbuild src\windows\Stella.sln


artifacts:
  - path: '**\stella.exe'
